export const ClaimerData = [{
        key: "1",
        name: "Jane Cooper",
        staffName: "Jane Cooper",
        claimDate: "2025-02-07",
        totalWorking: "538 hours",
        totalClaimAmount: "15,541,000 VND",
        projectName: "Health Care",
        status: "Draft",
        staffImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ronald",
        email: "jane.cooper@example.com",
        phone: "1234-456-789",
        phoneNumber: "1234-123-123",
        approvedBy: "Approver account",
        projectStartDate: "2025-01-07",
        projectEndDate: "2025-02-07",
        reason: "Completed project milestone and overtime work during system deployment",
        address: "123 Main Street, City, Country",
        staffId: "DE123",
        roleInProject: "dev"
    },
    {
        key: "2",
        name: "Floyd Miller",
        staffName: "Floyd Miller",
        claimDate: "2025-02-05",
        totalWorking: "533 hours",
        totalClaimAmount: "15,541,000 VND",
        projectName: "Health Care",
        status: "Pending",
        staffImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ronald",
        email: "floyd.miller@example.com",
        phone: "1234-456-789",
        phoneNumber: "1234-456-789",
        approvedBy: "Approver account",
        projectStartDate: "2025-01-05",
        projectEndDate: "2025-02-05",
        reason: "Extended working hours for critical feature implementation",
        address: "456 Secondary St, City, Country",
        staffId: "DE123",
        roleInProject: "ba"
    }, {
        key: "3",
        name: "Ronald Richards",
        staffName: "Ronald Richards",
        claimDate: "2025-02-03",
        totalWorking: "558 hours",
        totalClaimAmount: "15,541,001 VND",
        projectName: "Functional Auto Door",
        status: "Pending",
        staffImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ronald",
        email: "ronald.richards@example.com",
        phone: "1234-456-789",
        phoneNumber: "1234-789-123",
        approvedBy: "Approver account",
        projectStartDate: "2025-01-03",
        projectEndDate: "2025-02-03",
        reason: "Weekend support for system maintenance and updates",
        address: "789 Tertiary Ave, City, Country",
        staffId: "DE123",
        roleInProject: "dev"
    }, {
        key: "4",
        name: "Marvin McKinney",
        staffName: "Marvin McKinney",
        claimDate: "2025-02-01",
        totalWorking: "538 hours",
        totalClaimAmount: "15,541,000 VND",
        projectName: "Functional Auto Door",
        status: "Approved",
        staffImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ronald",
        email: "marvin.mckinney@example.com",
        phone: "1234-456-789",
        phoneNumber: "1234-321-321",
        approvedBy: "Approver account",
        projectStartDate: "2025-01-01",
        projectEndDate: "2025-02-01",
        reason: "Met project milestones with excellent performance",
        address: "321 Example Blvd, City, Country",
        staffId: "DE123",
        roleInProject: "ba"
    }, {
        key: "5",
        name: "Jerome Bell",
        staffName: "Jerome Bell",
        claimDate: "2025-01-28",
        totalWorking: "548 hours",
        totalClaimAmount: "15,541,000 VND",
        projectName: "Functional Fish care",
        status: "Pending",
        staffImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ronald",
        email: "jerome.bell@example.com",
        phone: "1234-456-789",
        phoneNumber: "1234-654-987",
        approvedBy: "Approver account",
        projectStartDate: "2025-01-10",
        projectEndDate: "2025-01-28",
        reason: "Completed maintenance with positive feedback from client",
        address: "654 Marine Drive, City, Country",
        staffId: "DE123",
        roleInProject: "dev"
    }, {
        key: "6",
        name: "Kathryn Murphy",
        staffName: "Kathryn Murphy",
        claimDate: "2025-01-25",
        totalWorking: "531 hours",
        totalClaimAmount: "15,541,002 VND",
        projectName: "Health Care",
        status: "Pending",
        staffImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ronald",
        email: "kathryn.murphy@example.com",
        phone: "1234-456-789",
        phoneNumber: "1234-987-654",
        approvedBy: "Approver account",
        projectStartDate: "2025-01-05",
        projectEndDate: "2025-01-25",
        reason: "Worked extra hours during critical period",
        address: "987 Health St, City, Country",
        staffId: "DE123",
        roleInProject: "ba"
    }, {
        key: "7",
        name: "Jacob Jones",
        staffName: "Jacob Jones",
        claimDate: "2025-01-20",
        totalWorking: "539 hours",
        totalClaimAmount: "15,541,004 VND",
        projectName: "Functional Fish care",
        status: "Pending",
        staffImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ronald",
        email: "jacob.jones@example.com",
        phone: "1234-456-789",
        phoneNumber: "1234-111-222",
        approvedBy: "Approver account",
        projectStartDate: "2025-01-01",
        projectEndDate: "2025-01-20",
        reason: "Managed project efficiently and maintained quality",
        address: "111 Ocean Ave, City, Country",
        staffId: "DE123",
        roleInProject: "dev"
    }, {
        key: "8",
        name: "Kristin Watson",
        staffName: "Kristin Watson",
        claimDate: "2025-01-15",
        totalWorking: "535 hours",
        totalClaimAmount: "15,541,003 VND",
        projectName: "Functional Auto Door",
        status: "Pending",
        staffImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ronald",
        email: "kristin.watson@example.com",
        phone: "1234-456-789",
        phoneNumber: "1234-333-444",
        approvedBy: "Approver account",
        projectStartDate: "2025-01-05",
        projectEndDate: "2025-01-15",
        reason: "Pending review for additional work hours",
        address: "333 Auto Lane, City, Country",
        staffId: "DE123",
        roleInProject: "ba"
    }, {
        key: "9",
        name: "Alice Johnson",
        staffName: "Alice Johnson",
        claimDate: "2025-02-08",
        totalWorking: "520 hours",
        totalClaimAmount: "15,541,100 VND",
        projectName: "Marketing",
        status: "Pending",
        staffImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ronald",
        email: "alice.johnson@example.com",
        phone: "1234-456-789",
        phoneNumber: "1234-555-666",
        approvedBy: "Approver account",
        projectStartDate: "2025-02-01",
        projectEndDate: "2025-02-08",
        reason: "Campaign launch extended working hours",
        address: "555 Business Rd, City, Country",
        staffId: "DE123",
        roleInProject: "dev"
    }, {
        key: "10",
        name: "Bob Williams",
        staffName: "Bob Williams",
        claimDate: "2025-02-09",
        totalWorking: "540 hours",
        totalClaimAmount: "15,541,200 VND",
        projectName: "Finance",
        status: "Pending",
        staffImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ronald",
        email: "bob.williams@example.com",
        phone: "1234-456-789",
        phoneNumber: "1234-777-888",
        approvedBy: "Approver account",
        projectStartDate: "2025-02-02",
        projectEndDate: "2025-02-09",
        reason: "Budget reconciliation overtime",
        address: "777 Finance St, City, Country",
        staffId: "DE123",
        roleInProject: "ba"
    },
    // Dữ liệu mới
    {
        key: "11",
        name: "Michael Scott",
        staffName: "Michael Scott",
        claimDate: "2025-02-10",
        totalWorking: "545 hours",
        totalClaimAmount: "15,541,500 VND",
        projectName: "Sales",
        status: "Approved",
        staffImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
        email: "michael.scott@example.com",
        phone: "1234-456-789",
        phoneNumber: "1234-888-999",
        approvedBy: "Approver account",
        projectStartDate: "2025-02-03",
        projectEndDate: "2025-02-10",
        reason: "Exceeded quarterly sales targets",
        address: "1725 Slough Ave, Scranton, PA, USA",
        staffId: "DE123",
        roleInProject: "dev"
    }, {
        key: "12",
        name: "Dwight Schrute",
        staffName: "Dwight Schrute",
        claimDate: "2025-02-11",
        totalWorking: "550 hours",
        totalClaimAmount: "15,541,700 VND",
        projectName: "Sales",
        status: "Pending",
        staffImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dwight",
        email: "dwight.schrute@example.com",
        phone: "1234-456-789",
        phoneNumber: "1234-000-111",
        approvedBy: "Approver account",
        projectStartDate: "2025-02-04",
        projectEndDate: "2025-02-11",
        reason: "Handled additional client meetings and support",
        address: "99 Beet Farm Rd, Scranton, PA, USA",
        staffId: "DE123",
        roleInProject: "ba"
    }, {
        key: "13",
        name: "Jim Halpert",
        staffName: "Jim Halpert",
        claimDate: "2025-02-12",
        totalWorking: "530 hours",
        totalClaimAmount: "15,541,300 VND",
        projectName: "Marketing",
        status: "Approved",
        staffImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jim",
        email: "jim.halpert@example.com",
        phone: "1234-456-789",
        phoneNumber: "1234-222-333",
        approvedBy: "Approver account",
        projectStartDate: "2025-02-05",
        projectEndDate: "2025-02-12",
        reason: "Contributed to campaign strategy and client engagement",
        address: "1725 Branch St, Scranton, PA, USA",
        staffId: "DE123",
        roleInProject: "dev"
    }, {
        key: "14",
        name: "Pam Beesly",
        staffName: "Pam Beesly",
        claimDate: "2025-02-13",
        totalWorking: "525 hours",
        totalClaimAmount: "15,541,100 VND",
        projectName: "Design",
        status: "Rejected",
        staffImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Pam",
        email: "pam.beesly@example.com",
        phoneNumber: "1234-444-555",
        approvedBy: "Approver account",
        projectStartDate: "2025-02-06",
        projectEndDate: "2025-02-13",
        reason: "Design revisions did not meet client expectations",
        address: "456 Art Blvd, Scranton, PA, USA",
        staffId: "DE123",
        roleInProject: "ba"
    }, {
        key: "15",
        name: "Stanley Hudson",
        staffName: "Stanley Hudson",
        claimDate: "2025-02-14",
        totalWorking: "540 hours",
        totalClaimAmount: "15,541,800 VND",
        projectName: "Sales",
        status: "Pending",
        staffImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Stanley",
        email: "stanley.hudson@example.com",
        phoneNumber: "1234-666-777",
        approvedBy: "Approver account",
        projectStartDate: "2025-02-07",
        projectEndDate: "2025-02-14",
        reason: "Provided consistent support for major client accounts",
        address: "789 Sales St, Scranton, PA, USA",
        staffId: "DE123",
        roleInProject: "dev"
    },
];